config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show, :edit, :update]
  resources :analyses, only: [:create, :index]

  root 'static_pages#index'

  get '/auth/twitter/callback', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  resources :searches, only: [:index, :show, :create, :update]


 post '/results', to: "searches#search_results"
 get '/results', to: "searches#search_results_display"
end

app/models/analysis.rb
class Analysis < ActiveRecord::Base
  
end

app/models/aylien_analyze.rb
require_relative "../services/aylien_sentiment_service"

class AylienAnalyze
  
  def initialize
    @service = AylienSentimentService.new
  end
  
  def analyze_tweets(tweets) 
    tweets.map do |tweet|
      a = AnalysisGroup.new
      a.sentiment = @service.analyze(tweet)["polarity"]
      a.polarity = @service.analyze(tweet)["polarity_confidence"]
      a
    end
  end
  
  def grouped_analysis(tweets)
    grouped = analyze_tweets(tweets).group_by { |thing| thing.sentiment }
    grouped.map { | k, v| grouped[k] = [ v.count, (v.reduce(0) { |sum, t| sum + t.polarity }/ v.count) ] }
    grouped
  end    
end

class AnalysisGroup < OpenStruct
  
end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :user

  def self.run_saved_searches
    count = 0
    aylien = AylienAnalyze.new
    where(active?: true).each do |search|
      tweets = SearchResults.new(search.word).all_tweets.map do |tweet|
        tweet.text
      end
      analyze = aylien.grouped_analysis(tweets)
      analysis = Analysis.create(user_id: search.user_id, keyword: search.word, analysis: analyze)
      UserMailer.daily_digest_email(search.user, analysis).deliver_later
      count += 1
      sleep(45)
    end
    puts "#{count} searches analyzed."
  end
end

app/models/search_results.rb
class SearchResults
  attr_reader :service

  def initialize(search)
    @search = search
  end

  def service
    @service ||= TwittersearchService.new
  end

  def all_tweets
    TwittersearchService.new.search_by(@search).map do |tweet|
      t = Tweet.new
      t.text = tweet.attrs[:text]
      t.created_at = tweet.attrs[:created_at]
      t.screen_name = tweet.attrs[:user][:screen_name]
      t
    end
  end
end

class Tweet < OpenStruct

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :searches
  has_many :analyses

  def self.find_or_create_from_auth(auth)
    user = find_or_create_by(
    provider: auth.provider,
    uid:  auth.uid
    )

    user.nickname  = auth.info.nickname
    user.name      = auth.info.name
    user.location  = auth.info.location
    user.image_url = auth.info.image
    user.token     = auth.credentials.token
    user.save!

    user
  end

  def email?
    if email.nil?
      false
    else
      true
    end
  end
end

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController

  def index
    word         = session["word"]
    tweets       = SearchResults.new(word).all_tweets
    tweets_array = tweets.map { |tweet| tweet.text }
    user_id      = session["user_id"]

    analyze      = AylienAnalyze.new.grouped_analysis(tweets_array)

    @analysis    = Analysis.create(user_id: user_id, keyword: word, analysis: analyze)

    redirect_to user_path(current_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :check_email

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def check_email
    if current_user && current_user.email? == false
      redirect_to edit_user_path(current_user)
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  respond_to :json

  def index
    if current_user
      @saved_searches = Search.where(user_id: current_user.id, active?: true)
    end
  end

  def show
  end

  def create
    @search = Search.new(search_params)
   
    if @search.save
      @search.update(user_id: current_user.id)
      flash.now[:success] = " #{@search.word} is a saved search!"
      redirect_to searches_path
    end
  end
  
  def update
    @search = Search.find(params["id"])
    if @search.update(active?: false)
      flash[:success] = "Your search for #{@search.word} has been deactivated."
      redirect_to searches_path
    end
  end

  def search_results
    @word          = params["word"]
    session[:word] = @word
    @tweets        = SearchResults.new(@word).all_tweets
    respond_with @tweets, status: 201, location: user_path(current_user)
  end
  
  private
  
  def search_params
    params.require(:search).permit(:user_id, :word, :active?)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_email, only: :create
  def create
    user = User.find_or_create_from_auth(auth)

    if user
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to root_path
    end
  end

  def destroy
    session.clear

    redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :check_email
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :check_email, :only => [:edit, :update]

  def show
    @analyses = Analysis.where(user_id: current_user.id)  
  end

  def edit
  end

  def update
    if current_user.update(email: params[:user][:email])
      redirect_to user_path(current_user)
    end
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users/searches_helper.rb
module Users::SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
  <footer class="cyan darken-2">
    <div class="container z-depth-2">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="yellow-text text-lighten-1">About Us</h5>
          <p class="light white-text text-lighten-4">We are a group of students at the Turing School of Software and Design, a seven-month immersive web-development training program teaching full-stack Ruby and Javascript. If you like what you see here, feel free to reach out!</p>

        </div>
        <div class="col l3 s12">
          <h5 class="yellow-text text-lighten-3">LinkedIn</h5>
          <ul>
            <li><a class="white-text" href="https://www.linkedin.com/in/davidjdaniel">David</a></li>
            <li><a class="white-text" href="https://github.com/kristinabrown">Kristina</a></li>
            <li><a class="white-text" href="https://www.linkedin.com/in/patrickmedaugh">Patrick</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="yellow-text text-lighten-3">GitHub</h5>
          <ul>
            <li><a class="white-text" href="https://github.com/davedan7">Daniel</a></li>
            <li><a class="white-text" href="https://github.com/kristinabrown">Brown</a></li>
            <li><a class="white-text" href="http://www.github.com/patrickmedaugh">Medaugh</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright cyan darken-2">
      <div class="container">
      Powered by <a class="orange-text text-lighten-4" href="http://www.turing.io">Turing</a>
      </div>
    </div>
  </footer>

app/views/layouts/_nav.html.erb
<nav class="cyan darken-2" role="navigation">
  <div class="nav-wrapper container">
  <a id="logo-container" href="/" class="brand-logo white-text" id="logo">tweetsum</a>
    <ul class="right hide-on-med-and-down">
      <% if current_user.nil? %>
        <li><%= link_to "login with twitter", "/auth/twitter", class: "white-text" %></li>
      <% else %>
        <li><%= image_tag current_user.image_url, class: "responsive-img", id: "profile-pic" %></li>
        <li><%= link_to "Dashboard", user_path(current_user), class: "white-text" %></li>
        <li><%= link_to "logout", logout_path, method: "delete", class: "white-text" %></li>
      <% end %>
    </ul>

    <ul id="nav-mobile" class="side-nav">
      <li><%= link_to "login with twitter", "/auth/twitter", class: "white-text" %>
    </ul>


    <!-- Mobile nav -->
    <ul id="nav-mobile" class="side-nav">
      <li><a class="waves-effect waves-light btn"><i class="mdi-file-cloud left z-depth-3"></i>Sign Up</a></li>
      <li><a href="/find">Search</a></li>
      <li><a href="/learn-more">Learn More</a></li>
      <!-- <li><a href="#">Navbar Link</a></li> -->
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>

  </div>
</nav>

app/views/layouts/_new_nav.html.erb
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content nav-item">
  <% if current_user %>
  <li><p><%= link_to "Search tweets", user_path(current_user) %></p></li>
  <li><p><%= link_to "Saved Searches", searches_path %></p></li>
  <li class="divider"></li>
  <% end %>
</ul>

<nav class="cyan darken-2" role="navigation">
  <div class="nav-wrapper container">
    <a id="logo-container" href="/" class="brand-logo white-text" id="logo">tweetsum</a>
    <ul class="right hide-on-med-and-down">
      <% if current_user.nil? %>
        <li><%= link_to "Login with twitter", "/auth/twitter", class: "white-text" %></li>
      <% else %>
        <li><%= image_tag current_user.image_url, class: "responsive-img", id: "profile-pic" %></li>
        <li ><a class="dropdown-button white-text" href="#!" data-activates="dropdown1">Your Dashboard<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
        <li><%= link_to "Sign Out", logout_path, method: "delete", class: "white-text" %></li>
      <% end %>
    </ul>

    <!-- Mobile Navbar -->
    <ul id="nav-mobile" class="side-nav cyan darken-2">
      <% if current_user.nil? %>
        <li><%= link_to "login with twitter", "/auth/twitter", class: "white-text" %>
      <% else %>
        <li><%= link_to "Dashboard", user_path(current_user), class: "white-text" %></li>
        <li><%= link_to "Sign Out", logout_path, method: "delete", class: "white-text" %></li>
      <% end %>
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
  </div>
</nav

app/views/layouts/_throttle.html.erb
<div class="container center">
<head>
      <meta http-equiv="content-type" content="text/html;charset=utf-8">
      <title>d3.js gauges</title>
    
    <style>
    
      body
      {
          font: 10px arial;
      }
      
    </style>
    
    <script type="text/javascript" src="http://mbostock.github.com/d3/d3.js"></script>
    <script type="text/javascript" src="gauge.js"></script>
 
    <script>
            
        
      var gauges = [];
      
      function createGauge(name, label, min, max)
      {
        var config = 
        {
          size: 120,
          label: label,
          min: undefined != min ? min : 0,
          max: undefined != max ? max : 100,
          minorTicks: 5
        }
        
        var range = config.max - config.min;
        config.yellowZones = [{ from: config.min + range*0.75, to: config.min + range*0.9 }];
        config.redZones = [{ from: config.min + range*0.9, to: config.max }];
        
        gauges[name] = new Gauge(name + "GaugeContainer", config);
        gauges[name].render();
      }
      
      function createGauges()
      {
        createGauge("memory", "Confidence");
        createGauge("cpu", "Sentiment");
        createGauge("network", "Polarity");
        //createGauge("test", "Test", -50, 50 );
      }
      
      function updateGauges()
      {
        for (var key in gauges)
        {
          var value = getRandomValue(gauges[key])
          gauges[key].redraw(value);
        }
      }
      
      function getRandomValue(gauge)
      {
        var overflow = 0; //10;
        return gauge.config.min - overflow + (gauge.config.max - gauge.config.min + overflow*2) *  Math.random();
      }
      
      function initialize()
      {
        createGauges();
        setInterval(updateGauges, 5000);
      }
      
    </script>
    
    
  </head>
  
  <body onload="initialize()">
    <span id="memoryGaugeContainer"></span>
    <span id="cpuGaugeContainer"></span>
    <span id="networkGaugeContainer"></span>
    <span id="testGaugeContainer"></span>
  </body>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeedEngine</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "materialize.css" %>
  <%= stylesheet_link_tag "style.css" %>
  
</head>
<body>
  
<%= render :partial => 'layouts/new_nav.html.erb' %>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :class => "flash-#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/searches/index.html.erb
<div class="row search-div">
  <div class="col s6 offset-s3">
    <%= form_tag searches_path, method: "post" do %>
    <i class="mdi-action-search prefix"></i>
      <%= label_tag "Save Search" %>
      <%= text_field_tag "search[word]" %>
      <%= hidden_field_tag :user_id, current_user.id %>
      <%= submit_tag "New Save Search", class: "btn cyan darken-2" %>
      <a href="#!" class="btn cyan darken-2" onclick="Materialize.showStaggeredList('#staggered-test')">Show Saved Searches</a>
    <% end %>
  </div>
</div>

<div class="row user-header">
  <div class="col s3 offset-s2">
    <ul id="staggered-test">
  <% @saved_searches.each do |ss| %>
      <li class="saved-search-item"><h6><strong>Word:</strong> '<%= ss.word %>' <br><%= link_to "Remove", search_path(ss), method: "patch" %></h6> </li><br>
  <% end %>
    </ul>
  </div>
</div>

<% @saved_searches.each do |ss| %>
<div class="positive hidden">
  <% positive = [] %>
  <% @saved_searches.each do |ss| %>
    <% Analysis.where(keyword: ss.word).each do |a| %>
      <% a.analysis.each do |k, v| %>
        <% if k == "positive" %>
          <% positive << (v.split(",").first.to_s.delete!("[")) %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <%= positive %>
</div>

<div class="negative hidden">
  <% positive = [] %>
  <% @saved_searches.each do |ss| %>
    <% Analysis.where(keyword: ss.word).each do |a| %>
      <% a.analysis.each do |k, v| %>
        <% if k == "negative" %>
          <% positive << (v.split(",").first.to_s.delete!("[")) %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <%= positive %>
</div>

<div class="neutral hidden">
  <% positive = [] %>
  <% @saved_searches.each do |ss| %>
    <% Analysis.where(keyword: ss.word).each do |a| %>
      <% a.analysis.each do |k, v| %>
        <% if k == "neutral" %>
          <% positive << (v.split(",").first.to_s.delete!("[")) %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <%= positive %>
</div>

  <%= ss.word %>
  <div class="chart"></div>
<% end %>
  


<!-- <div class="row user-header">
  <div class="col s4 offset-s2">
      <table class="centered hoverable responsive-table teal lighten-3">
        <thead>
          <h6>Current Saved Searches</h6>
          <tr>
            <th data-field="name">Word</th>
            <th data-field="boolean">Active?</th>
            <th></th>
          </tr>
        <thead>
          <tbody>
            <%# @saved_searches.each do |ss| %>
            <tr>
              <td><%#= ss.word %></td>
              <td><%#= ss.active? %></td>
            <td><%#= link_to "Deactivate", search_path(ss), method: "patch" %>
            </tr>
          </tbody>
          <%# end %>
      </table>
  </div>
</div>
 -->

app/views/searches/search_results_display.html.erb
<div class="container center-align">
  <h2><%= @word %></h2>
</div>
  <% @array_of_text = [] %>
  <% @tweets.each do |tweet| %>
  <% @array_of_text << "#{tweet.text}|||||" %>
  <% end %>

<div class="row">
  <div class="col s2">
    <%= form_tag "/analyses", method: "post" do  %>
        <%= hidden_field_tag :tweets, @array_of_text %>
        <%= hidden_field_tag :word, @word %>
        <%= hidden_field_tag :user_id, current_user.id %>
        <%= submit_tag "Analyze", class: "btn" %>
    <% end %>
  </div>
  <div class="col s3">
    <%= form_tag searches_path, method: "post" do %>
      <%= hidden_field_tag "search[word]", @word %>
      <%= hidden_field_tag :user_id, current_user.id %>
      <%= submit_tag "Save Search", class: "btn" %>
    <% end %>
  </div>
</div>

  
<div class="row">
  <% @tweets.each do |tweet| %>
  <div class="col s12 m4">
    <div class="card blue-grey darken-1 tweet-cards z-depth-3 display-cards">
      <div class="card-content white-text">
        <span class="card-title"><%= link_to "@#{tweet.screen_name}", "https://twitter.com/#{tweet.screen_name}", target: "_blank" %></span>

        <p> <%= tweet.text %> </p>

      </div>
      <div class="card-action card-foot blue-text text-lighten-4">
        <h6><%= tweet.created_at.to_date %></h6>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/searches/throttle.html.erb
<div class="container center">
<head>
      <meta http-equiv="content-type" content="text/html;charset=utf-8">
      <title>d3.js gauges</title>
    
    <style>
    
      body
      {
          font: 10px arial;
      }
      
    </style>
    
    <script type="text/javascript" src="http://mbostock.github.com/d3/d3.js"></script>
    <script type="text/javascript" src="gauge.js"></script>
 
    <script>
            
        
      var gauges = [];
      
      function createGauge(name, label, min, max)
      {
        var config = 
        {
          size: 120,
          label: label,
          min: undefined != min ? min : 0,
          max: undefined != max ? max : 100,
          minorTicks: 5
        }
        
        var range = config.max - config.min;
        config.yellowZones = [{ from: config.min + range*0.75, to: config.min + range*0.9 }];
        config.redZones = [{ from: config.min + range*0.9, to: config.max }];
        
        gauges[name] = new Gauge(name + "GaugeContainer", config);
        gauges[name].render();
      }
      
      function createGauges()
      {
        createGauge("memory", "Memory");
        createGauge("cpu", "CPU");
        createGauge("network", "Network");
        //createGauge("test", "Test", -50, 50 );
      }
      
      function updateGauges()
      {
        for (var key in gauges)
        {
          var value = getRandomValue(gauges[key])
          gauges[key].redraw(value);
        }
      }
      
      function getRandomValue(gauge)
      {
        var overflow = 0; //10;
        return gauge.config.min - overflow + (gauge.config.max - gauge.config.min + overflow*2) *  Math.random();
      }
      
      function initialize()
      {
        createGauges();
        setInterval(updateGauges, 5000);
      }
      
    </script>
    
    
  </head>
  
  <body onload="initialize()">
    <span id="memoryGaugeContainer"></span>
    <span id="cpuGaugeContainer"></span>
    <span id="networkGaugeContainer"></span>
    <span id="testGaugeContainer"></span>
  </body>
  </div>

app/views/static_pages/index.html.erb
<body id="landing-background">
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="header center teal-text text-darken-2">tweetsum</h1>
      <div class="row center">
        <h5 class="header col s12 landing-quote teal-text text-darken-3">Providing a scheduled summary of your twitter sentiment.</h5>
      </div>
      <br><br>

    </div>
  </div>
  <div class="parallax"><%= image_tag("throttle.png", alt: "Unsplashed background img 1") %></div>
</div>


<div class="container">
  <div class="section">

    <!--   Icon Section   -->
    <ul id="staggered-test">

    <li class="homeInfo">
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center black-text"><i class="mdi-action-search"></i></h2>
          <h5 class="center cyan-text text-darken-2">Quick Search</h5>

          <p class="light">Enter a keyword or twitter handle and get a fast summary of what people are saying.</p> </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center black-text"><i class="mdi-content-content-paste"></i></h2>
          <h5 class="center cyan-text text-darken-2">Analyze</h5>

          <p class="light">Utilize Natural Language Processing to analyze and rate an overall sentiment for your searches</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center black-text"><i class="mdi-action-trending-up"></i></h2>
          <h5 class="center cyan-text text-darken-2">Track Trends</h5>

          <p class="center light">Schedule an automated email to track how a saved search is trending over time.</p>
        </div>
      </div>
    </div>

    </li>
    </ol>

  </div>
</div>



<div class="container">
  <div class="section">


  </div>
</div>


<!-- old -->
<!--  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <ul class="collapsible" data-collapsible="accordion">
        <li>
          <div class="collapsible-header cyan darken-1 white-text"><i class="mdi-action-search"></i>Quick Search</div>
          <div class="collapsible-body cyan lighten-4"><p>Enter a keyword or twitter handle and get a fast analysis of what people are saying.</p></div>
        </li>
        <li>
          <div class="collapsible-header cyan darken-2 white-text"><i class="mdi-content-content-paste"></i>Save a Search</div>
          <div class="collapsible-body cyan lighten-4"><p>Save a search, and receive a daily email digest with a full analysis.</p></div>
        </li>
        <li>
          <div class="collapsible-header cyan darken-3 white-text"><i class="mdi-action-trending-up"></i>Track Trends Over Time</div>
          <div class="collapsible-body cyan lighten-4"><p>Check your dashboard to see how a saved search is trending over time.</p></div>
        </li>
      </ul>

    </div>
  </div>
 -->
</body>
<<%= render :partial => 'layouts/throttle.html.erb' %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<%= render :partial => 'layouts/footer.html.erb' %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col s5">
    <p>Please enter your email information</p>
  </div>
</div>
<div class="row">
  <div class="col s6 offset-s1">
    <%= form_for current_user do |f| %>
    <i class="mdi-communication-email prefix"></i>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.submit "Update Email", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!-- testing -->
<br>
<br>
  <div class="row search-div">
  <div class="col s6 offset-s3">
    <i class="mdi-action-search prefix search"></i>
    <label for="searchword">Quick Search</label>
    <input id="search" class="searchword" type="search" required>
    <input type="submit" value="Submit "class="btn searchTweet cyan darken-2 ">
  </div>
</div>


<!-- display -->
<div class="row" id="tweets">
</div>
<!-- end testing -->

<% @analyses.each do |a| %>
<div class="row">
  <div class="col s3">
    <h4><%= a.keyword %></h4>
    <div class="col s4">
      <h6><%= a.created_at.to_date %></h6>
    </div>
  </div>
  
<div class="row">
  <table class="centered hoverable responsive-table analyses-table teal lighten-4">
    <thead>
      <tr>
        <th data-field="number">Number</th>
        <th data-field="name">Sentiment</th>
        <th data-field="number">Polarity</th>
      </tr>
    <thead>
    <tbody>
      <% a.analysis.each do |k, v| %>
      <tr>
        <td><%= v.split(",").first.to_s.delete!("[") %></td>
        <td><%= k %></td>
        <td><%= v.split(",").last.to_s.delete!("]").to_f.round(3) %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
  <% end %>
</div>